mysql-enable: false
redis:
  hostname: localhost
  port: 6379
  user: NONE
  password: clouddev
mysql:
  hostname: hostname
  port: 3306
  database: database
  username: username
  password: password
  prefix: redissocial

