server-name: 'oneblock1'
hostname: hostname
port: 3306
database: database
username: username
password: password
cooldown-confirmation: 10
spawn-world: world
keep-inventory: false
redis:
  enabled: false
  hostname: 192.168.1.102
  port: 6379
  password: password
  log: false

#How many threads are used to calculate the level of an island!
threads_level: 4

radius:
  member:
    tiers: '25,50,75,100'
    permission: 'oneblock.radius.member'
  noble:
    tiers: '30,55,80,105'
    permission: 'oneblock.radius.noble'