name: OneBlock
version: BETA-0.2.3
main: ro.deiutzblaxo.oneblock.OneBlock
author: JDeiutz
api-version: 1.16
softdepend:
  - RoyaleEconomy
commands:
  island:
    aliases: [ is ]
  message:
    aliases: [ msg,pm ]
  global:
  islandadmin:

